<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AssemblySeat;

class AssemblySeatsSeeder extends Seeder
{
    public function run()
    {
        $seats = [
            // ============================================================
            // 1–50: Saharanpur to Meerut South
            // ============================================================
            ['seat_number' => 1, 'seat_name' => 'Behat', 'district' => 'Saharanpur'],
            ['seat_number' => 2, 'seat_name' => 'Nakur', 'district' => 'Saharanpur'],
            ['seat_number' => 3, 'seat_name' => 'Saharanpur Nagar', 'district' => 'Saharanpur'],
            ['seat_number' => 4, 'seat_name' => 'Saharanpur', 'district' => 'Saharanpur'],
            ['seat_number' => 5, 'seat_name' => 'Deoband', 'district' => 'Saharanpur'],
            ['seat_number' => 6, 'seat_name' => 'Rampur Maniharan (SC)', 'district' => 'Saharanpur'],
            ['seat_number' => 7, 'seat_name' => 'Gangoh', 'district' => 'Saharanpur'],
            ['seat_number' => 8, 'seat_name' => 'Kairana', 'district' => 'Shamli'],
            ['seat_number' => 9, 'seat_name' => 'Thana Bhawan', 'district' => 'Shamli'],
            ['seat_number' => 10, 'seat_name' => 'Shamli', 'district' => 'Shamli'],
            ['seat_number' => 11, 'seat_name' => 'Budhana', 'district' => 'Muzaffarnagar'],
            ['seat_number' => 12, 'seat_name' => 'Charthawal', 'district' => 'Muzaffarnagar'],
            ['seat_number' => 13, 'seat_name' => 'Purqazi (SC)', 'district' => 'Muzaffarnagar'],
            ['seat_number' => 14, 'seat_name' => 'Muzaffar Nagar', 'district' => 'Muzaffarnagar'],
            ['seat_number' => 15, 'seat_name' => 'Khatauli', 'district' => 'Muzaffarnagar'],
            ['seat_number' => 16, 'seat_name' => 'Meerapur', 'district' => 'Muzaffarnagar'],
            ['seat_number' => 17, 'seat_name' => 'Najibabad', 'district' => 'Bijnor'],
            ['seat_number' => 18, 'seat_name' => 'Nagina (SC)', 'district' => 'Bijnor'],
            ['seat_number' => 19, 'seat_name' => 'Barhapur', 'district' => 'Bijnor'],
            ['seat_number' => 20, 'seat_name' => 'Dhampur', 'district' => 'Bijnor'],
            ['seat_number' => 21, 'seat_name' => 'Nehtaur (SC)', 'district' => 'Bijnor'],
            ['seat_number' => 22, 'seat_name' => 'Bijnor', 'district' => 'Bijnor'],
            ['seat_number' => 23, 'seat_name' => 'Chandpur', 'district' => 'Bijnor'],
            ['seat_number' => 24, 'seat_name' => 'Noorpur', 'district' => 'Bijnor'],
            ['seat_number' => 25, 'seat_name' => 'Kanth', 'district' => 'Moradabad'],
            ['seat_number' => 26, 'seat_name' => 'Thakurdwara', 'district' => 'Moradabad'],
            ['seat_number' => 27, 'seat_name' => 'Moradabad Rural', 'district' => 'Moradabad'],
            ['seat_number' => 28, 'seat_name' => 'Moradabad Nagar', 'district' => 'Moradabad'],
            ['seat_number' => 29, 'seat_name' => 'Kundarki', 'district' => 'Moradabad'],
            ['seat_number' => 30, 'seat_name' => 'Bilari', 'district' => 'Moradabad'],
            ['seat_number' => 31, 'seat_name' => 'Chandausi (SC)', 'district' => 'Sambhal'],
            ['seat_number' => 32, 'seat_name' => 'Asmoli', 'district' => 'Sambhal'],
            ['seat_number' => 33, 'seat_name' => 'Sambhal', 'district' => 'Sambhal'],
            ['seat_number' => 34, 'seat_name' => 'Suar', 'district' => 'Rampur'],
            ['seat_number' => 35, 'seat_name' => 'Chamraua', 'district' => 'Rampur'],
            ['seat_number' => 36, 'seat_name' => 'Bilaspur', 'district' => 'Rampur'],
            ['seat_number' => 37, 'seat_name' => 'Rampur', 'district' => 'Rampur'],
            ['seat_number' => 38, 'seat_name' => 'Milak (SC)', 'district' => 'Rampur'],
            ['seat_number' => 39, 'seat_name' => 'Dhanaura (SC)', 'district' => 'Amroha'],
            ['seat_number' => 40, 'seat_name' => 'Naugawan Sadat', 'district' => 'Amroha'],
            ['seat_number' => 41, 'seat_name' => 'Amroha', 'district' => 'Amroha'],
            ['seat_number' => 42, 'seat_name' => 'Hasanpur', 'district' => 'Amroha'],
            ['seat_number' => 43, 'seat_name' => 'Siwalkhas', 'district' => 'Meerut'],
            ['seat_number' => 44, 'seat_name' => 'Sardhana', 'district' => 'Meerut'],
            ['seat_number' => 45, 'seat_name' => 'Hastinapur (SC)', 'district' => 'Meerut'],
            ['seat_number' => 46, 'seat_name' => 'Kithore', 'district' => 'Meerut'],
            ['seat_number' => 47, 'seat_name' => 'Meerut Cantt.', 'district' => 'Meerut'],
            ['seat_number' => 48, 'seat_name' => 'Meerut', 'district' => 'Meerut'],
            ['seat_number' => 49, 'seat_name' => 'Meerut South', 'district' => 'Meerut'],
            ['seat_number' => 50, 'seat_name' => 'Chhaprauli', 'district' => 'Baghpat'],

            // ============================================================
            // 51–100: Baghpat to Kasganj
            // ============================================================
            ['seat_number' => 51, 'seat_name' => 'Baraut', 'district' => 'Baghpat'],
            ['seat_number' => 52, 'seat_name' => 'Baghpat', 'district' => 'Baghpat'],
            ['seat_number' => 53, 'seat_name' => 'Loni', 'district' => 'Ghaziabad'],
            ['seat_number' => 54, 'seat_name' => 'Muradnagar', 'district' => 'Ghaziabad'],
            ['seat_number' => 55, 'seat_name' => 'Sahibabad', 'district' => 'Ghaziabad'],
            ['seat_number' => 56, 'seat_name' => 'Ghaziabad', 'district' => 'Ghaziabad'],
            ['seat_number' => 57, 'seat_name' => 'Modi Nagar', 'district' => 'Ghaziabad'],
            ['seat_number' => 58, 'seat_name' => 'Dhaulana', 'district' => 'Ghaziabad'],
            ['seat_number' => 59, 'seat_name' => 'Hapur (SC)', 'district' => 'Hapur'],
            ['seat_number' => 60, 'seat_name' => 'Garhmukteshwar', 'district' => 'Hapur'],
            ['seat_number' => 61, 'seat_name' => 'Noida', 'district' => 'Gautam Buddha Nagar'],
            ['seat_number' => 62, 'seat_name' => 'Dadri', 'district' => 'Gautam Buddha Nagar'],
            ['seat_number' => 63, 'seat_name' => 'Jewar', 'district' => 'Gautam Buddha Nagar'],
            ['seat_number' => 64, 'seat_name' => 'Sikandrabad', 'district' => 'Bulandshahr'],
            ['seat_number' => 65, 'seat_name' => 'Bulandshahr', 'district' => 'Bulandshahr'],
            ['seat_number' => 66, 'seat_name' => 'Syana', 'district' => 'Bulandshahr'],
            ['seat_number' => 67, 'seat_name' => 'Anupshahr', 'district' => 'Bulandshahr'],
            ['seat_number' => 68, 'seat_name' => 'Debai', 'district' => 'Bulandshahr'],
            ['seat_number' => 69, 'seat_name' => 'Shikarpur', 'district' => 'Bulandshahr'],
            ['seat_number' => 70, 'seat_name' => 'Khurja (SC)', 'district' => 'Bulandshahr'],
            ['seat_number' => 71, 'seat_name' => 'Khair (SC)', 'district' => 'Aligarh'],
            ['seat_number' => 72, 'seat_name' => 'Baroli', 'district' => 'Aligarh'],
            ['seat_number' => 73, 'seat_name' => 'Atrauli', 'district' => 'Aligarh'],
            ['seat_number' => 74, 'seat_name' => 'Chharra', 'district' => 'Aligarh'],
            ['seat_number' => 75, 'seat_name' => 'Koil', 'district' => 'Aligarh'],
            ['seat_number' => 76, 'seat_name' => 'Aligarh', 'district' => 'Aligarh'],
            ['seat_number' => 77, 'seat_name' => 'Iglas (SC)', 'district' => 'Aligarh'],
            ['seat_number' => 78, 'seat_name' => 'Hathras (SC)', 'district' => 'Hathras'],
            ['seat_number' => 79, 'seat_name' => 'Sadabad', 'district' => 'Hathras'],
            ['seat_number' => 80, 'seat_name' => 'Sikandra Rao', 'district' => 'Hathras'],
            ['seat_number' => 81, 'seat_name' => 'Chhata', 'district' => 'Mathura'],
            ['seat_number' => 82, 'seat_name' => 'Mant', 'district' => 'Mathura'],
            ['seat_number' => 83, 'seat_name' => 'Goverdhan', 'district' => 'Mathura'],
            ['seat_number' => 84, 'seat_name' => 'Mathura', 'district' => 'Mathura'],
            ['seat_number' => 85, 'seat_name' => 'Baldev (SC)', 'district' => 'Mathura'],
            ['seat_number' => 86, 'seat_name' => 'Etmadpur', 'district' => 'Agra'],
            ['seat_number' => 87, 'seat_name' => 'Agra Cantt. (SC)', 'district' => 'Agra'],
            ['seat_number' => 88, 'seat_name' => 'Agra South', 'district' => 'Agra'],
            ['seat_number' => 89, 'seat_name' => 'Agra North', 'district' => 'Agra'],
            ['seat_number' => 90, 'seat_name' => 'Agra Rural (SC)', 'district' => 'Agra'],
            ['seat_number' => 91, 'seat_name' => 'Fatehpur Sikri', 'district' => 'Agra'],
            ['seat_number' => 92, 'seat_name' => 'Kheragarh', 'district' => 'Agra'],
            ['seat_number' => 93, 'seat_name' => 'Fatehabad', 'district' => 'Agra'],
            ['seat_number' => 94, 'seat_name' => 'Bah', 'district' => 'Agra'],
            ['seat_number' => 95, 'seat_name' => 'Tundla (SC)', 'district' => 'Firozabad'],
            ['seat_number' => 96, 'seat_name' => 'Jasrana', 'district' => 'Firozabad'],
            ['seat_number' => 97, 'seat_name' => 'Firozabad', 'district' => 'Firozabad'],
            ['seat_number' => 98, 'seat_name' => 'Shikohabad', 'district' => 'Firozabad'],
            ['seat_number' => 99, 'seat_name' => 'Sirsaganj', 'district' => 'Firozabad'],
            ['seat_number' => 100, 'seat_name' => 'Kasganj', 'district' => 'Kasganj'],

            // ============================================================
            // 101–150: Amanpur to Mahmoodabad
            // ============================================================
            ['seat_number' => 101, 'seat_name' => 'Amanpur', 'district' => 'Kasganj'],
            ['seat_number' => 102, 'seat_name' => 'Patiyali', 'district' => 'Kasganj'],
            ['seat_number' => 103, 'seat_name' => 'Aliganj', 'district' => 'Etah'],
            ['seat_number' => 104, 'seat_name' => 'Etah', 'district' => 'Etah'],
            ['seat_number' => 105, 'seat_name' => 'Marhara', 'district' => 'Etah'],
            ['seat_number' => 106, 'seat_name' => 'Jalesar (SC)', 'district' => 'Etah'],
            ['seat_number' => 107, 'seat_name' => 'Mainpuri', 'district' => 'Mainpuri'],
            ['seat_number' => 108, 'seat_name' => 'Bhongaon', 'district' => 'Mainpuri'],
            ['seat_number' => 109, 'seat_name' => 'Kishni (SC)', 'district' => 'Mainpuri'],
            ['seat_number' => 110, 'seat_name' => 'Karhal', 'district' => 'Mainpuri'],
            ['seat_number' => 111, 'seat_name' => 'Gunnaur', 'district' => 'Sambhal'],
            ['seat_number' => 112, 'seat_name' => 'Bisauli (SC)', 'district' => 'Sambhal'],
            ['seat_number' => 113, 'seat_name' => 'Sahaswan', 'district' => 'Budaun'],
            ['seat_number' => 114, 'seat_name' => 'Bilsi', 'district' => 'Budaun'],
            ['seat_number' => 115, 'seat_name' => 'Badaun', 'district' => 'Budaun'],
            ['seat_number' => 116, 'seat_name' => 'Shekhupur', 'district' => 'Budaun'],
            ['seat_number' => 117, 'seat_name' => 'Dataganj', 'district' => 'Budaun'],
            ['seat_number' => 118, 'seat_name' => 'Baheri', 'district' => 'Bareilly'],
            ['seat_number' => 119, 'seat_name' => 'Meerganj', 'district' => 'Bareilly'],
            ['seat_number' => 120, 'seat_name' => 'Bhojipura', 'district' => 'Bareilly'],
            ['seat_number' => 121, 'seat_name' => 'Nawabganj', 'district' => 'Bareilly'],
            ['seat_number' => 122, 'seat_name' => 'Faridpur (SC)', 'district' => 'Bareilly'],
            ['seat_number' => 123, 'seat_name' => 'Bithari Chainpur', 'district' => 'Bareilly'],
            ['seat_number' => 124, 'seat_name' => 'Bareilly', 'district' => 'Bareilly'],
            ['seat_number' => 125, 'seat_name' => 'Bareilly Cantt.', 'district' => 'Bareilly'],
            ['seat_number' => 126, 'seat_name' => 'Aonla', 'district' => 'Bareilly'],
            ['seat_number' => 127, 'seat_name' => 'Pilibhit', 'district' => 'Pilibhit'],
            ['seat_number' => 128, 'seat_name' => 'Barkhera', 'district' => 'Pilibhit'],
            ['seat_number' => 129, 'seat_name' => 'Puranpur (SC)', 'district' => 'Pilibhit'],
            ['seat_number' => 130, 'seat_name' => 'Bisalpur', 'district' => 'Pilibhit'],
            ['seat_number' => 131, 'seat_name' => 'Katra', 'district' => 'Shahjahanpur'],
            ['seat_number' => 132, 'seat_name' => 'Jalalabad', 'district' => 'Shahjahanpur'],
            ['seat_number' => 133, 'seat_name' => 'Tilhar', 'district' => 'Shahjahanpur'],
            ['seat_number' => 134, 'seat_name' => 'Powayan (SC)', 'district' => 'Shahjahanpur'],
            ['seat_number' => 135, 'seat_name' => 'Shahjahanpur', 'district' => 'Shahjahanpur'],
            ['seat_number' => 136, 'seat_name' => 'Dadraul', 'district' => 'Shahjahanpur'],
            ['seat_number' => 137, 'seat_name' => 'Palia', 'district' => 'Kheri'],
            ['seat_number' => 138, 'seat_name' => 'Nighasan', 'district' => 'Kheri'],
            ['seat_number' => 139, 'seat_name' => 'Gola Gokrannath', 'district' => 'Kheri'],
            ['seat_number' => 140, 'seat_name' => 'Sri Nagar (SC)', 'district' => 'Kheri'],
            ['seat_number' => 141, 'seat_name' => 'Dhaurahra', 'district' => 'Kheri'],
            ['seat_number' => 142, 'seat_name' => 'Lakhimpur', 'district' => 'Kheri'],
            ['seat_number' => 143, 'seat_name' => 'Kasta (SC)', 'district' => 'Kheri'],
            ['seat_number' => 144, 'seat_name' => 'Mohammdi', 'district' => 'Kheri'],
            ['seat_number' => 145, 'seat_name' => 'Maholi', 'district' => 'Sitapur'],
            ['seat_number' => 146, 'seat_name' => 'Sitapur', 'district' => 'Sitapur'],
            ['seat_number' => 147, 'seat_name' => 'Hargaon (SC)', 'district' => 'Sitapur'],
            ['seat_number' => 148, 'seat_name' => 'Laharpur', 'district' => 'Sitapur'],
            ['seat_number' => 149, 'seat_name' => 'Biswan', 'district' => 'Sitapur'],
            ['seat_number' => 150, 'seat_name' => 'Sevata', 'district' => 'Sitapur'],

            // ============================================================
            // 151–200: Mahmoodabad to Etawah
            // ============================================================
            ['seat_number' => 151, 'seat_name' => 'Mahmoodabad', 'district' => 'Sitapur'],
            ['seat_number' => 152, 'seat_name' => 'Sidhauli (SC)', 'district' => 'Sitapur'],
            ['seat_number' => 153, 'seat_name' => 'Misrikh (SC)', 'district' => 'Sitapur'],
            ['seat_number' => 154, 'seat_name' => 'Sawayazpur', 'district' => 'Hardoi'],
            ['seat_number' => 155, 'seat_name' => 'Shahabad', 'district' => 'Hardoi'],
            ['seat_number' => 156, 'seat_name' => 'Hardoi', 'district' => 'Hardoi'],
            ['seat_number' => 157, 'seat_name' => 'Gopamau (SC)', 'district' => 'Hardoi'],
            ['seat_number' => 158, 'seat_name' => 'Sandi (SC)', 'district' => 'Hardoi'],
            ['seat_number' => 159, 'seat_name' => 'Bilgram-Mallanwan', 'district' => 'Hardoi'],
            ['seat_number' => 160, 'seat_name' => 'Balamau (SC)', 'district' => 'Hardoi'],
            ['seat_number' => 161, 'seat_name' => 'Sandila', 'district' => 'Hardoi'],
            ['seat_number' => 162, 'seat_name' => 'Bangermau', 'district' => 'Unnao'],
            ['seat_number' => 163, 'seat_name' => 'Safipur (SC)', 'district' => 'Unnao'],
            ['seat_number' => 164, 'seat_name' => 'Mohan (SC)', 'district' => 'Unnao'],
            ['seat_number' => 165, 'seat_name' => 'Unnao', 'district' => 'Unnao'],
            ['seat_number' => 166, 'seat_name' => 'Bhagwantnagar', 'district' => 'Unnao'],
            ['seat_number' => 167, 'seat_name' => 'Purwa', 'district' => 'Unnao'],
            ['seat_number' => 168, 'seat_name' => 'Malihabad (SC)', 'district' => 'Lucknow'],
            ['seat_number' => 169, 'seat_name' => 'Bakshi Kaa Talab', 'district' => 'Lucknow'],
            ['seat_number' => 170, 'seat_name' => 'Sarojini Nagar', 'district' => 'Lucknow'],
            ['seat_number' => 171, 'seat_name' => 'Lucknow West', 'district' => 'Lucknow'],
            ['seat_number' => 172, 'seat_name' => 'Lucknow North', 'district' => 'Lucknow'],
            ['seat_number' => 173, 'seat_name' => 'Lucknow East', 'district' => 'Lucknow'],
            ['seat_number' => 174, 'seat_name' => 'Lucknow Central', 'district' => 'Lucknow'],
            ['seat_number' => 175, 'seat_name' => 'Lucknow Cantt.', 'district' => 'Lucknow'],
            ['seat_number' => 176, 'seat_name' => 'Mohanlalganj (SC)', 'district' => 'Lucknow'],
            ['seat_number' => 177, 'seat_name' => 'Bachhrawan (SC)', 'district' => 'Rae Bareli'],
            ['seat_number' => 178, 'seat_name' => 'Tiloi', 'district' => 'Rae Bareli'],
            ['seat_number' => 179, 'seat_name' => 'Harchandpur', 'district' => 'Rae Bareli'],
            ['seat_number' => 180, 'seat_name' => 'Rae Bareli', 'district' => 'Rae Bareli'],
            ['seat_number' => 181, 'seat_name' => 'Salon (SC)', 'district' => 'Rae Bareli'],
            ['seat_number' => 182, 'seat_name' => 'Sareni', 'district' => 'Rae Bareli'],
            ['seat_number' => 183, 'seat_name' => 'Unchahar', 'district' => 'Rae Bareli'],
            ['seat_number' => 184, 'seat_name' => 'Jagdishpur (SC)', 'district' => 'Amethi'],
            ['seat_number' => 185, 'seat_name' => 'Gauriganj', 'district' => 'Amethi'],
            ['seat_number' => 186, 'seat_name' => 'Amethi', 'district' => 'Amethi'],
            ['seat_number' => 187, 'seat_name' => 'Isauli', 'district' => 'Sultanpur'],
            ['seat_number' => 188, 'seat_name' => 'Sultanpur', 'district' => 'Sultanpur'],
            ['seat_number' => 189, 'seat_name' => 'Sadar', 'district' => 'Sultanpur'],
            ['seat_number' => 190, 'seat_name' => 'Lambhua', 'district' => 'Sultanpur'],
            ['seat_number' => 191, 'seat_name' => 'Kadipur (SC)', 'district' => 'Sultanpur'],
            ['seat_number' => 192, 'seat_name' => 'Kaimganj (SC)', 'district' => 'Farrukhabad'],
            ['seat_number' => 193, 'seat_name' => 'Amritpur', 'district' => 'Farrukhabad'],
            ['seat_number' => 194, 'seat_name' => 'Farrukhabad', 'district' => 'Farrukhabad'],
            ['seat_number' => 195, 'seat_name' => 'Bhojpur', 'district' => 'Farrukhabad'],
            ['seat_number' => 196, 'seat_name' => 'Chhibramau', 'district' => 'Kannauj'],
            ['seat_number' => 197, 'seat_name' => 'Tirwa', 'district' => 'Kannauj'],
            ['seat_number' => 198, 'seat_name' => 'Kannauj (SC)', 'district' => 'Kannauj'],
            ['seat_number' => 199, 'seat_name' => 'Jaswantnagar', 'district' => 'Etawah'],
            ['seat_number' => 200, 'seat_name' => 'Etawah', 'district' => 'Etawah'],

            // ============================================================
            // 201–250: Bharthana to Raniganj
            // ============================================================
            ['seat_number' => 201, 'seat_name' => 'Bharthana (SC)', 'district' => 'Etawah'],
            ['seat_number' => 202, 'seat_name' => 'Bidhuna', 'district' => 'Auraiya'],
            ['seat_number' => 203, 'seat_name' => 'Dibiyapur', 'district' => 'Auraiya'],
            ['seat_number' => 204, 'seat_name' => 'Auraiya (SC)', 'district' => 'Auraiya'],
            ['seat_number' => 205, 'seat_name' => 'Rasulabad (SC)', 'district' => 'Kanpur Dehat'],
            ['seat_number' => 206, 'seat_name' => 'Akbarpur-Raniya', 'district' => 'Kanpur Dehat'],
            ['seat_number' => 207, 'seat_name' => 'Sikandra', 'district' => 'Kanpur Dehat'],
            ['seat_number' => 208, 'seat_name' => 'Bhognipur', 'district' => 'Kanpur Dehat'],
            ['seat_number' => 209, 'seat_name' => 'Bilhaur (SC)', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 210, 'seat_name' => 'Bithoor', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 211, 'seat_name' => 'Kalyanpur', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 212, 'seat_name' => 'Govindnagar', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 213, 'seat_name' => 'Sishamau', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 214, 'seat_name' => 'Arya Nagar', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 215, 'seat_name' => 'Kidwai Nagar', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 216, 'seat_name' => 'Kanpur Cantt.', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 217, 'seat_name' => 'Maharajpur', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 218, 'seat_name' => 'Ghatampur (SC)', 'district' => 'Kanpur Nagar'],
            ['seat_number' => 219, 'seat_name' => 'Madhaugarh', 'district' => 'Jalaun'],
            ['seat_number' => 220, 'seat_name' => 'Kalpi', 'district' => 'Jalaun'],
            ['seat_number' => 221, 'seat_name' => 'Orai (SC)', 'district' => 'Jalaun'],
            ['seat_number' => 222, 'seat_name' => 'Babina', 'district' => 'Jhansi'],
            ['seat_number' => 223, 'seat_name' => 'Jhansi Nagar', 'district' => 'Jhansi'],
            ['seat_number' => 224, 'seat_name' => 'Mauranipur (SC)', 'district' => 'Jhansi'],
            ['seat_number' => 225, 'seat_name' => 'Garautha', 'district' => 'Jhansi'],
            ['seat_number' => 226, 'seat_name' => 'Lalitpur', 'district' => 'Lalitpur'],
            ['seat_number' => 227, 'seat_name' => 'Mehroni (SC)', 'district' => 'Lalitpur'],
            ['seat_number' => 228, 'seat_name' => 'Hamirpur', 'district' => 'Hamirpur'],
            ['seat_number' => 229, 'seat_name' => 'Rath (SC)', 'district' => 'Hamirpur'],
            ['seat_number' => 230, 'seat_name' => 'Mahoba', 'district' => 'Mahoba'],
            ['seat_number' => 231, 'seat_name' => 'Charkhari', 'district' => 'Mahoba'],
            ['seat_number' => 232, 'seat_name' => 'Tindwari', 'district' => 'Banda'],
            ['seat_number' => 233, 'seat_name' => 'Baberu', 'district' => 'Banda'],
            ['seat_number' => 234, 'seat_name' => 'Naraini (SC)', 'district' => 'Banda'],
            ['seat_number' => 235, 'seat_name' => 'Banda', 'district' => 'Banda'],
            ['seat_number' => 236, 'seat_name' => 'Chitrakoot', 'district' => 'Chitrakoot'],
            ['seat_number' => 237, 'seat_name' => 'Manikpur', 'district' => 'Chitrakoot'],
            ['seat_number' => 238, 'seat_name' => 'Jahanabad', 'district' => 'Fatehpur'],
            ['seat_number' => 239, 'seat_name' => 'Bindki', 'district' => 'Fatehpur'],
            ['seat_number' => 240, 'seat_name' => 'Fatehpur', 'district' => 'Fatehpur'],
            ['seat_number' => 241, 'seat_name' => 'Ayah Shah', 'district' => 'Fatehpur'],
            ['seat_number' => 242, 'seat_name' => 'Husainganj', 'district' => 'Fatehpur'],
            ['seat_number' => 243, 'seat_name' => 'Khaga (SC)', 'district' => 'Fatehpur'],
            ['seat_number' => 244, 'seat_name' => 'Rampur Khas', 'district' => 'Pratapgarh'],
            ['seat_number' => 245, 'seat_name' => 'Babaganj (SC)', 'district' => 'Pratapgarh'],
            ['seat_number' => 246, 'seat_name' => 'Kunda', 'district' => 'Pratapgarh'],
            ['seat_number' => 247, 'seat_name' => 'Vishwanath Ganj', 'district' => 'Pratapgarh'],
            ['seat_number' => 248, 'seat_name' => 'Pratapgarh', 'district' => 'Pratapgarh'],
            ['seat_number' => 249, 'seat_name' => 'Patti', 'district' => 'Pratapgarh'],
            ['seat_number' => 250, 'seat_name' => 'Raniganj', 'district' => 'Pratapgarh'],

            // ============================================================
            // 251–300: Sirathu to Mankapur (SC)
            // ============================================================
            ['seat_number' => 251, 'seat_name' => 'Sirathu', 'district' => 'Kaushambi'],
            ['seat_number' => 252, 'seat_name' => 'Manjhanpur (SC)', 'district' => 'Kaushambi'],
            ['seat_number' => 253, 'seat_name' => 'Chail', 'district' => 'Kaushambi'],
            ['seat_number' => 254, 'seat_name' => 'Phaphamau', 'district' => 'Prayagraj'],
            ['seat_number' => 255, 'seat_name' => 'Soraon (SC)', 'district' => 'Prayagraj'],
            ['seat_number' => 256, 'seat_name' => 'Phulpur', 'district' => 'Prayagraj'],
            ['seat_number' => 257, 'seat_name' => 'Pratappur', 'district' => 'Prayagraj'],
            ['seat_number' => 258, 'seat_name' => 'Handia', 'district' => 'Prayagraj'],
            ['seat_number' => 259, 'seat_name' => 'Meja', 'district' => 'Prayagraj'],
            ['seat_number' => 260, 'seat_name' => 'Karachhana', 'district' => 'Prayagraj'],
            ['seat_number' => 261, 'seat_name' => 'Allahabad West', 'district' => 'Prayagraj'],
            ['seat_number' => 262, 'seat_name' => 'Allahabad North', 'district' => 'Prayagraj'],
            ['seat_number' => 263, 'seat_name' => 'Allahabad South', 'district' => 'Prayagraj'],
            ['seat_number' => 264, 'seat_name' => 'Bara (SC)', 'district' => 'Prayagraj'],
            ['seat_number' => 265, 'seat_name' => 'Koraon (SC)', 'district' => 'Prayagraj'],
            ['seat_number' => 266, 'seat_name' => 'Kursi', 'district' => 'Barabanki'],
            ['seat_number' => 267, 'seat_name' => 'Ram Nagar', 'district' => 'Barabanki'],
            ['seat_number' => 268, 'seat_name' => 'Barabanki', 'district' => 'Barabanki'],
            ['seat_number' => 269, 'seat_name' => 'Zaidpur (SC)', 'district' => 'Barabanki'],
            ['seat_number' => 270, 'seat_name' => 'Dariyabad', 'district' => 'Barabanki'],
            ['seat_number' => 271, 'seat_name' => 'Rudauli', 'district' => 'Ayodhya'],
            ['seat_number' => 272, 'seat_name' => 'Haidergarh (SC)', 'district' => 'Ayodhya'],
            ['seat_number' => 273, 'seat_name' => 'Milkipur (SC)', 'district' => 'Ayodhya'],
            ['seat_number' => 274, 'seat_name' => 'Bikapur', 'district' => 'Ayodhya'],
            ['seat_number' => 275, 'seat_name' => 'Ayodhya', 'district' => 'Ayodhya'],
            ['seat_number' => 276, 'seat_name' => 'Goshainganj', 'district' => 'Ayodhya'],
            ['seat_number' => 277, 'seat_name' => 'Katehari', 'district' => 'Ambedkar Nagar'],
            ['seat_number' => 278, 'seat_name' => 'Tanda', 'district' => 'Ambedkar Nagar'],
            ['seat_number' => 279, 'seat_name' => 'Alapur (SC)', 'district' => 'Ambedkar Nagar'],
            ['seat_number' => 280, 'seat_name' => 'Jalalpur', 'district' => 'Ambedkar Nagar'],
            ['seat_number' => 281, 'seat_name' => 'Akbarpur', 'district' => 'Ambedkar Nagar'],
            ['seat_number' => 282, 'seat_name' => 'Balha (SC)', 'district' => 'Bahraich'],
            ['seat_number' => 283, 'seat_name' => 'Nanpara', 'district' => 'Bahraich'],
            ['seat_number' => 284, 'seat_name' => 'Matera', 'district' => 'Bahraich'],
            ['seat_number' => 285, 'seat_name' => 'Mahasi', 'district' => 'Bahraich'],
            ['seat_number' => 286, 'seat_name' => 'Bahraich', 'district' => 'Bahraich'],
            ['seat_number' => 287, 'seat_name' => 'Payagpur', 'district' => 'Bahraich'],
            ['seat_number' => 288, 'seat_name' => 'Kaiserganj', 'district' => 'Bahraich'],
            ['seat_number' => 289, 'seat_name' => 'Bhinga', 'district' => 'Shravasti'],
            ['seat_number' => 290, 'seat_name' => 'Shrawasti', 'district' => 'Shravasti'],
            ['seat_number' => 291, 'seat_name' => 'Tulsipur', 'district' => 'Balrampur'],
            ['seat_number' => 292, 'seat_name' => 'Gainsari', 'district' => 'Balrampur'],
            ['seat_number' => 293, 'seat_name' => 'Utraula', 'district' => 'Balrampur'],
            ['seat_number' => 294, 'seat_name' => 'Balrampur (SC)', 'district' => 'Balrampur'],
            ['seat_number' => 295, 'seat_name' => 'Mehnaun', 'district' => 'Balrampur'],
            ['seat_number' => 296, 'seat_name' => 'Gonda', 'district' => 'Gonda'],
            ['seat_number' => 297, 'seat_name' => 'Katra Bazar', 'district' => 'Gonda'],
            ['seat_number' => 298, 'seat_name' => 'Colonelganj', 'district' => 'Gonda'],
            ['seat_number' => 299, 'seat_name' => 'Tarabganj', 'district' => 'Gonda'],
            ['seat_number' => 300, 'seat_name' => 'Mankapur (SC)', 'district' => 'Gonda'],

            // ============================================================
            // 301–350: Gaura to Didarganj
            // ============================================================
            ['seat_number' => 301, 'seat_name' => 'Gaura', 'district' => 'Gonda'],
            ['seat_number' => 302, 'seat_name' => 'Shohratgarh', 'district' => 'Siddharthnagar'],
            ['seat_number' => 303, 'seat_name' => 'Kapilvastu (SC)', 'district' => 'Siddharthnagar'],
            ['seat_number' => 304, 'seat_name' => 'Bansi', 'district' => 'Siddharthnagar'],
            ['seat_number' => 305, 'seat_name' => 'Itwa', 'district' => 'Siddharthnagar'],
            ['seat_number' => 306, 'seat_name' => 'Domariyaganj', 'district' => 'Siddharthnagar'],
            ['seat_number' => 307, 'seat_name' => 'Harraiya', 'district' => 'Basti'],
            ['seat_number' => 308, 'seat_name' => 'Kaptanganj', 'district' => 'Basti'],
            ['seat_number' => 309, 'seat_name' => 'Rudhauli', 'district' => 'Basti'],
            ['seat_number' => 310, 'seat_name' => 'Basti Sadar', 'district' => 'Basti'],
            ['seat_number' => 311, 'seat_name' => 'Mahadewa (SC)', 'district' => 'Basti'],
            ['seat_number' => 312, 'seat_name' => 'Menhdawal', 'district' => 'Sant Kabir Nagar'],
            ['seat_number' => 313, 'seat_name' => 'Khalilabad', 'district' => 'Sant Kabir Nagar'],
            ['seat_number' => 314, 'seat_name' => 'Dhanghata (SC)', 'district' => 'Sant Kabir Nagar'],
            ['seat_number' => 315, 'seat_name' => 'Pharenda', 'district' => 'Maharajganj'],
            ['seat_number' => 316, 'seat_name' => 'Nautanwa', 'district' => 'Maharajganj'],
            ['seat_number' => 317, 'seat_name' => 'Siswa', 'district' => 'Maharajganj'],
            ['seat_number' => 318, 'seat_name' => 'Maharajganj (SC)', 'district' => 'Maharajganj'],
            ['seat_number' => 319, 'seat_name' => 'Paniyara', 'district' => 'Maharajganj'],
            ['seat_number' => 320, 'seat_name' => 'Caimpiyarganj', 'district' => 'Gorakhpur'],
            ['seat_number' => 321, 'seat_name' => 'Pipraich', 'district' => 'Gorakhpur'],
            ['seat_number' => 322, 'seat_name' => 'Gorakhpur Urban', 'district' => 'Gorakhpur'],
            ['seat_number' => 323, 'seat_name' => 'Gorakhpur Rural', 'district' => 'Gorakhpur'],
            ['seat_number' => 324, 'seat_name' => 'Sahajanwa', 'district' => 'Gorakhpur'],
            ['seat_number' => 325, 'seat_name' => 'Khajani (SC)', 'district' => 'Gorakhpur'],
            ['seat_number' => 326, 'seat_name' => 'Chauri-Chaura', 'district' => 'Gorakhpur'],
            ['seat_number' => 327, 'seat_name' => 'Bansgaon (SC)', 'district' => 'Gorakhpur'],
            ['seat_number' => 328, 'seat_name' => 'Chillupar', 'district' => 'Gorakhpur'],
            ['seat_number' => 329, 'seat_name' => 'Khadda', 'district' => 'Kushinagar'],
            ['seat_number' => 330, 'seat_name' => 'Padrauna', 'district' => 'Kushinagar'],
            ['seat_number' => 331, 'seat_name' => 'Tamkuhi Raj', 'district' => 'Kushinagar'],
            ['seat_number' => 332, 'seat_name' => 'Fazilnagar', 'district' => 'Kushinagar'],
            ['seat_number' => 333, 'seat_name' => 'Kushinagar', 'district' => 'Kushinagar'],
            ['seat_number' => 334, 'seat_name' => 'Hata', 'district' => 'Kushinagar'],
            ['seat_number' => 335, 'seat_name' => 'Ramkola (SC)', 'district' => 'Kushinagar'],
            ['seat_number' => 336, 'seat_name' => 'Rudrapur', 'district' => 'Deoria'],
            ['seat_number' => 337, 'seat_name' => 'Deoria', 'district' => 'Deoria'],
            ['seat_number' => 338, 'seat_name' => 'Pathardeva', 'district' => 'Deoria'],
            ['seat_number' => 339, 'seat_name' => 'Rampur Karkhana', 'district' => 'Deoria'],
            ['seat_number' => 340, 'seat_name' => 'Bhatpar Rani', 'district' => 'Deoria'],
            ['seat_number' => 341, 'seat_name' => 'Salempur (SC)', 'district' => 'Deoria'],
            ['seat_number' => 342, 'seat_name' => 'Barhaj', 'district' => 'Deoria'],
            ['seat_number' => 343, 'seat_name' => 'Atrauliya', 'district' => 'Azamgarh'],
            ['seat_number' => 344, 'seat_name' => 'Gopalpur', 'district' => 'Azamgarh'],
            ['seat_number' => 345, 'seat_name' => 'Sagri', 'district' => 'Azamgarh'],
            ['seat_number' => 346, 'seat_name' => 'Mubarakpur', 'district' => 'Azamgarh'],
            ['seat_number' => 347, 'seat_name' => 'Azamgarh', 'district' => 'Azamgarh'],
            ['seat_number' => 348, 'seat_name' => 'Nizamabad', 'district' => 'Azamgarh'],
            ['seat_number' => 349, 'seat_name' => 'Phoolpur-Pawai', 'district' => 'Azamgarh'],
            ['seat_number' => 350, 'seat_name' => 'Didarganj', 'district' => 'Azamgarh'],

            // ============================================================
            // 351–403: Lalganj (SC) to Duddhi (SC)
            // ============================================================
            ['seat_number' => 351, 'seat_name' => 'Lalganj (SC)', 'district' => 'Azamgarh'],
            ['seat_number' => 352, 'seat_name' => 'Mehnagar (SC)', 'district' => 'Azamgarh'],
            ['seat_number' => 353, 'seat_name' => 'Madhuban', 'district' => 'Mau'],
            ['seat_number' => 354, 'seat_name' => 'Ghosi', 'district' => 'Mau'],
            ['seat_number' => 355, 'seat_name' => 'Muhammadabad-Gohna (SC)', 'district' => 'Mau'],
            ['seat_number' => 356, 'seat_name' => 'Mau', 'district' => 'Mau'],
            ['seat_number' => 357, 'seat_name' => 'Belthara Road (SC)', 'district' => 'Ballia'],
            ['seat_number' => 358, 'seat_name' => 'Rasara', 'district' => 'Ballia'],
            ['seat_number' => 359, 'seat_name' => 'Sikanderpur', 'district' => 'Ballia'],
            ['seat_number' => 360, 'seat_name' => 'Phephana', 'district' => 'Ballia'],
            ['seat_number' => 361, 'seat_name' => 'Ballia Nagar', 'district' => 'Ballia'],
            ['seat_number' => 362, 'seat_name' => 'Bansdih', 'district' => 'Ballia'],
            ['seat_number' => 363, 'seat_name' => 'Bairia', 'district' => 'Ballia'],
            ['seat_number' => 364, 'seat_name' => 'Badlapur', 'district' => 'Jaunpur'],
            ['seat_number' => 365, 'seat_name' => 'Shahganj', 'district' => 'Jaunpur'],
            ['seat_number' => 366, 'seat_name' => 'Jaunpur', 'district' => 'Jaunpur'],
            ['seat_number' => 367, 'seat_name' => 'Malhani', 'district' => 'Jaunpur'],
            ['seat_number' => 368, 'seat_name' => 'Mungra Badshahpur', 'district' => 'Jaunpur'],
            ['seat_number' => 369, 'seat_name' => 'Machhlishahr (SC)', 'district' => 'Jaunpur'],
            ['seat_number' => 370, 'seat_name' => 'Mariyahu', 'district' => 'Jaunpur'],
            ['seat_number' => 371, 'seat_name' => 'Zafrabad', 'district' => 'Jaunpur'],
            ['seat_number' => 372, 'seat_name' => 'Kerakat (SC)', 'district' => 'Jaunpur'],
            ['seat_number' => 373, 'seat_name' => 'Jakhanian (SC)', 'district' => 'Ghazipur'],
            ['seat_number' => 374, 'seat_name' => 'Saidpur (SC)', 'district' => 'Ghazipur'],
            ['seat_number' => 375, 'seat_name' => 'Ghazipur', 'district' => 'Ghazipur'],
            ['seat_number' => 376, 'seat_name' => 'Jangipur', 'district' => 'Ghazipur'],
            ['seat_number' => 377, 'seat_name' => 'Zahoorabad', 'district' => 'Ghazipur'],
            ['seat_number' => 378, 'seat_name' => 'Mohammadabad', 'district' => 'Ghazipur'],
            ['seat_number' => 379, 'seat_name' => 'Zamania', 'district' => 'Ghazipur'],
            ['seat_number' => 380, 'seat_name' => 'Mughalsarai', 'district' => 'Chandauli'],
            ['seat_number' => 381, 'seat_name' => 'Sakaldiha', 'district' => 'Chandauli'],
            ['seat_number' => 382, 'seat_name' => 'Saiyadraja', 'district' => 'Chandauli'],
            ['seat_number' => 383, 'seat_name' => 'Chakia (SC)', 'district' => 'Chandauli'],
            ['seat_number' => 384, 'seat_name' => 'Pindra', 'district' => 'Varanasi'],
            ['seat_number' => 385, 'seat_name' => 'Ajagara (SC)', 'district' => 'Varanasi'],
            ['seat_number' => 386, 'seat_name' => 'Shivpur', 'district' => 'Varanasi'],
            ['seat_number' => 387, 'seat_name' => 'Rohaniya', 'district' => 'Varanasi'],
            ['seat_number' => 388, 'seat_name' => 'Varanasi North', 'district' => 'Varanasi'],
            ['seat_number' => 389, 'seat_name' => 'Varanasi South', 'district' => 'Varanasi'],
            ['seat_number' => 390, 'seat_name' => 'Varanasi Cantt.', 'district' => 'Varanasi'],
            ['seat_number' => 391, 'seat_name' => 'Sevapuri', 'district' => 'Varanasi'],
            ['seat_number' => 392, 'seat_name' => 'Bhadohi', 'district' => 'Bhadohi'],
            ['seat_number' => 393, 'seat_name' => 'Gyanpur', 'district' => 'Bhadohi'],
            ['seat_number' => 394, 'seat_name' => 'Aurai (SC)', 'district' => 'Bhadohi'],
            ['seat_number' => 395, 'seat_name' => 'Chhanbey (SC)', 'district' => 'Mirzapur'],
            ['seat_number' => 396, 'seat_name' => 'Mirzapur', 'district' => 'Mirzapur'],
            ['seat_number' => 397, 'seat_name' => 'Majhawan', 'district' => 'Mirzapur'],
            ['seat_number' => 398, 'seat_name' => 'Chunar', 'district' => 'Mirzapur'],
            ['seat_number' => 399, 'seat_name' => 'Marihan', 'district' => 'Mirzapur'],
            ['seat_number' => 400, 'seat_name' => 'Ghorawal', 'district' => 'Sonbhadra'],
            ['seat_number' => 401, 'seat_name' => 'Robertsganj', 'district' => 'Sonbhadra'],
            ['seat_number' => 402, 'seat_name' => 'Obra', 'district' => 'Sonbhadra'],
            ['seat_number' => 403, 'seat_name' => 'Duddhi (SC)', 'district' => 'Sonbhadra'],
        ];

        foreach ($seats as $seat) {
            AssemblySeat::create($seat);
        }
    }
}